# Generated by Django 4.1 on 2023-01-05 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='payment_voucher',
        ),
    ]
