# Generated by Django 4.1 on 2023-01-06 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_payment_voucher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_voucher',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='receipt_voucher',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
