# Generated by Django 4.1 on 2023-01-24 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_alter_payment_voucher_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment_voucher',
            name='particulars',
        ),
        migrations.RemoveField(
            model_name='receipt_voucher',
            name='particulars',
        ),
        migrations.AlterField(
            model_name='payment_voucher',
            name='narration',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='receipt_voucher',
            name='narration',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
