# Generated by Django 4.1 on 2023-01-24 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_remove_payment_voucher_particulars_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt_voucher',
            name='voucher',
        ),
        migrations.DeleteModel(
            name='payment_voucher',
        ),
        migrations.DeleteModel(
            name='receipt_voucher',
        ),
    ]
