# Generated by Django 4.1 on 2023-01-24 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_remove_receipt_voucher_voucher_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='receipt_voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rid', models.IntegerField(null=True)),
                ('account', models.CharField(max_length=255, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('amount', models.IntegerField(null=True)),
                ('narration', models.CharField(max_length=255, null=True)),
                ('voucher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.voucher')),
            ],
        ),
        migrations.CreateModel(
            name='payment_voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField(null=True)),
                ('account', models.CharField(max_length=255, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('amount', models.IntegerField(null=True)),
                ('narration', models.CharField(max_length=255, null=True)),
                ('voucher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.voucher')),
            ],
        ),
    ]
