# Generated by Django 4.1 on 2023-01-30 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_receipt_voucher_payment_voucher'),
    ]

    operations = [
        migrations.CreateModel(
            name='transcation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transcation_type', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
