# Generated by Django 4.1 on 2023-02-03 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_transcation'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledger_chequebook',
            name='ledger_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
