# Generated by Django 4.1 on 2023-02-08 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_bank_transcations_delete_transcation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='bank_transcations',
        ),
    ]
