# Generated by Django 4.1 on 2023-02-14 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_bank_transcations'),
    ]

    operations = [
        migrations.AddField(
            model_name='tally_ledger',
            name='current_blnc',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tally_ledger',
            name='current_blnc_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
