# Generated by Django 4.1 on 2023-02-15 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_tally_ledger_current_blnc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='fmonths',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='stock_item_voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('Particulars', models.CharField(max_length=255, null=True)),
                ('Voucher_type', models.CharField(max_length=50)),
                ('Voucher_no', models.IntegerField(null=True)),
                ('rate', models.IntegerField(blank=True, null=True)),
                ('per', models.IntegerField(blank=True, null=True)),
                ('inwards_qty', models.IntegerField(blank=True, null=True)),
                ('inwards_val', models.IntegerField(blank=True, null=True)),
                ('outwards_qty', models.IntegerField(blank=True, null=True)),
                ('outwards_val', models.IntegerField(blank=True, null=True)),
                ('closing_qty', models.IntegerField(blank=True, null=True)),
                ('closing_val', models.IntegerField(blank=True, null=True)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.companies')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.stockgroupcreation')),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.stock_itemcreation')),
                ('month', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.fmonths')),
            ],
        ),
    ]
