# Generated by Django 4.1 on 2023-02-16 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0020_remove_stock_item_voucher_month_delete_fmonths'),
    ]

    operations = [
        migrations.CreateModel(
            name='fmonths',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='stock_item_voucher',
            name='month',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.fmonths'),
        ),
    ]
