# Generated by Django 4.1.4 on 2023-03-14 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0026_journal_voucher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journal_voucher',
            old_name='amount',
            new_name='credit',
        ),
        migrations.RemoveField(
            model_name='journal_voucher',
            name='account',
        ),
        migrations.AddField(
            model_name='journal_voucher',
            name='debit',
            field=models.IntegerField(null=True),
        ),
    ]
