# Generated by Django 4.1.4 on 2023-03-15 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0027_rename_amount_journal_voucher_credit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal_voucher',
            name='voucher_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
