# Generated by Django 4.1.4 on 2023-03-22 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0029_rename_voucher_name_journal_voucher_jname'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank_transcations',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.companies'),
        ),
        migrations.AddField(
            model_name='bank_transcations',
            name='pay_particular',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bank_transcations',
            name='pay_voucher',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bank_transcations',
            name='rec_particular',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bank_transcations',
            name='rec_voucher',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bank_transcations',
            name='voucher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.voucher'),
        ),
        migrations.AddField(
            model_name='journal_voucher',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.companies'),
        ),
        migrations.AddField(
            model_name='payment_voucher',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.companies'),
        ),
        migrations.AddField(
            model_name='receipt_voucher',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.companies'),
        ),
        migrations.CreateModel(
            name='receipt_particulars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('particular_id', models.IntegerField(null=True)),
                ('particular', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.IntegerField(null=True)),
                ('rec_voucher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.receipt_voucher')),
            ],
        ),
        migrations.CreateModel(
            name='payment_particulars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('particular_id', models.IntegerField(null=True)),
                ('particular', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.IntegerField(null=True)),
                ('pay_voucher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.payment_voucher')),
            ],
        ),
    ]
