# Generated by Django 4.1.4 on 2023-03-29 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0033_voucher_no_of_vouchers'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock_itemcreation',
            name='company',
            field=models.ForeignKey(default='null', on_delete=django.db.models.deletion.CASCADE, to='app1.companies'),
        ),
    ]
