# Generated by Django 4.1.4 on 2023-03-29 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0034_stock_itemcreation_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock_itemcreation',
            name='company',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app1.companies'),
        ),
    ]
