# Generated by Django 4.1.4 on 2023-03-29 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0035_alter_stock_itemcreation_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock_itemcreation',
            name='company',
        ),
    ]
